#!/bin/bash
set +e
BIN="$HOME/Documents/Claude/Projects/Valley Pawn OS/bin"
F="$HOME/Documents/Claude/Projects/Jewelry Count Reconciliation/STATUS.md"
bash "$BIN/append_line.sh" "$F" ""
bash "$BIN/append_line.sh" "$F" "## RUN 2026-10-02 (Friday) — jewelry-onhand-nightly-pull"
bash "$BIN/append_line.sh" "$F" "Freeze window: close 6pm (5pm Sat CUL/ROA) -> reopen 10am. Bravo pulls ran 20:41-22:37 (LEX and ROA needed one retry each after a mid-run Bravo stall; retries completed clean, self-heal + host-queue timeout handled it, no VM restart needed). PM count sheets read from fleet/eod_photos/2026-10-02/."
bash "$BIN/append_line.sh" "$F" "Open stores: CUL, HAR, LEX, ROA, WAY (Friday = all 5)."
bash "$BIN/append_line.sh" "$F" ""
bash "$BIN/append_line.sh" "$F" "| Store | Category | Expected | Counted | Variance |"
bash "$BIN/append_line.sh" "$F" "|---|---|---|---|---|"
bash "$BIN/append_line.sh" "$F" "| CUL | Rings | 672 | 672 | 0 |"
bash "$BIN/append_line.sh" "$F" "| CUL | Bracelets | 118 | 118 | 0 |"
bash "$BIN/append_line.sh" "$F" "| CUL | Earrings | 142 | 142 | 0 |"
bash "$BIN/append_line.sh" "$F" "| CUL | Pendants | 252 | 252 | 0 |"
bash "$BIN/append_line.sh" "$F" "| CUL | Necklaces | 150 | 150 | 0 |"
bash "$BIN/append_line.sh" "$F" "| CUL | Total | 1334 | 1334 | 0 |"
bash "$BIN/append_line.sh" "$F" "| HAR | Rings | 426 | n/a | sheet not posted |"
bash "$BIN/append_line.sh" "$F" "| HAR | Bracelets | 49 | n/a | sheet not posted |"
bash "$BIN/append_line.sh" "$F" "| HAR | Earrings | 46 | n/a | sheet not posted |"
bash "$BIN/append_line.sh" "$F" "| HAR | Pendants | 110 | n/a | sheet not posted |"
bash "$BIN/append_line.sh" "$F" "| HAR | Necklaces | 111 | n/a | sheet not posted |"
bash "$BIN/append_line.sh" "$F" "| HAR | Total | 742 | n/a | sheet not posted (Walker DM'd) |"
bash "$BIN/append_line.sh" "$F" "| LEX | Rings | 292 | 295 | +3 |"
bash "$BIN/append_line.sh" "$F" "| LEX | Bracelets | 37 | 38 | +1 |"
bash "$BIN/append_line.sh" "$F" "| LEX | Earrings | 46 | 46 | 0 |"
bash "$BIN/append_line.sh" "$F" "| LEX | Pendants | 52 | 51 | -1 |"
bash "$BIN/append_line.sh" "$F" "| LEX | Necklaces | 44 | 44 | 0 |"
bash "$BIN/append_line.sh" "$F" "| LEX | Total | 471 | 474 | +3 |"
bash "$BIN/append_line.sh" "$F" "| ROA | Rings | 576 | 576 | 0 |"
bash "$BIN/append_line.sh" "$F" "| ROA | Bracelets | 139 | 139 | 0 |"
bash "$BIN/append_line.sh" "$F" "| ROA | Earrings | 82 | 82 | 0 |"
bash "$BIN/append_line.sh" "$F" "| ROA | Pendants | 177 | 176 | -1 |"
bash "$BIN/append_line.sh" "$F" "| ROA | Necklaces | 154 | 155 | +1 |"
bash "$BIN/append_line.sh" "$F" "| ROA | Total | 1128 | 1128 | 0 |"
bash "$BIN/append_line.sh" "$F" "| WAY | Rings | 339 | 339 | 0 |"
bash "$BIN/append_line.sh" "$F" "| WAY | Bracelets | 43 | 43 | 0 |"
bash "$BIN/append_line.sh" "$F" "| WAY | Earrings | 58 | 58 | 0 |"
bash "$BIN/append_line.sh" "$F" "| WAY | Pendants | 66 | 66 | 0 |"
bash "$BIN/append_line.sh" "$F" "| WAY | Necklaces | 73 | 73 | 0 |"
bash "$BIN/append_line.sh" "$F" "| WAY | Total | 579 | 579 | 0 |"
bash "$BIN/append_line.sh" "$F" ""
bash "$BIN/append_line.sh" "$F" "Notes: LEX +3/+1 over (Rings/Bracelets) flags a possible non-recount issue, not loss -- LEX PM sheet has shown identical totals (295/38/44/46/51) every day since 9/29; DM'd Joshua. HAR jewelry sheet not posted tonight (only general EOD + gun count sheets came through) -- company post went out for CUL/LEX/ROA/WAY only, Walker DM'd for the sheet, per partial-post rule (employee-side gap, not a pipeline failure). Empty-category CSV rows treated as 0 and matched against prior-day CSV before use: HAR Charms (error both nights, consistent), LEX Charms (error both nights, consistent), LEX Brooches (error both nights, consistent), WAY Charms (error both nights, consistent). No category outside the known Charms/Brooches list came back error."
