DESC = {
 7:"Valley Pawn: no-credit-check pawn loans, gold & silver buying, and quality pre-owned merchandise at 5 Shenandoah Valley stores. Call or text your nearest shop.",
 8:"Find your nearest Valley Pawn. Five Virginia stores in Culpeper, Waynesboro, Harrisonburg, Lexington and Roanoke. Addresses, hours, phone numbers and directions.",
 9:"Fast, no-credit-check pawn loans at 5 Virginia locations. Bring an item of value, get cash the same day. No effect on your credit score. Call or text to ask first.",
 10:"Shop quality pre-owned tools, electronics, jewelry and instruments for less at Valley Pawn. Every item backed by a 30-day warranty. See this week's deals.",
 11:"Directions, phone numbers and store hours for all 5 Valley Pawn locations across Virginia's Shenandoah Valley. Call, text or stop in - no appointment needed.",
 146:"Straight answers on pawn loans, selling gold and silver, and buying pre-owned - from the Valley Pawn team across Virginia's Shenandoah Valley.",
 739:"Common questions about pawn loans, selling gold, ID requirements, interest, layaway and warranties - answered plainly by Valley Pawn in Virginia.",
 648:"FFL transfers handled at Valley Pawn. Bring your paperwork and we'll take care of the rest. Call ahead with any questions about fees and timing.",
 901:"Now hiring at Valley Pawn. Competitive pay, real advancement, and a team that treats people right. See open roles across our 5 Virginia stores and apply today.",
 833:"Shop Valley Pawn online. Quality pre-owned tools, electronics, jewelry and more from our 5 Virginia stores, all backed by a 30-day warranty.",
 867:"Browse in-store finds from all 5 Valley Pawn locations. Buy online and pick up at the store that has it. 30-day warranty on everything we sell.",
 881:"Valley Pawn returns and refund policy. Every item we sell carries a 30-day warranty. Here's exactly how returns and exchanges work.",
 1128:"Contact Valley Pawn. Phone, text and email for all 5 Shenandoah Valley stores, plus addresses, hours and directions.",
 419:"Valley Pawn Culpeper on James Madison Hwy - the only Valley Pawn open Monday through Saturday. Pawn loans, gold buying and quality pre-owned goods. Call or text.",
 420:"Valley Pawn Waynesboro on West Broad Street. No-credit-check pawn loans, gold and silver buying, and quality pre-owned merchandise. Call or text before you come.",
 421:"Valley Pawn Harrisonburg on East Market Street. Fast pawn loans, fair gold and silver offers, and quality pre-owned merchandise. Call or text us today.",
 422:"Valley Pawn Lexington on Walker Street. No-credit-check pawn loans, gold and silver buying, and quality pre-owned goods. Call or text before you stop in.",
 423:"Valley Pawn Roanoke on Peters Creek Road. Pawn loans, gold and silver buying, FFL transfers and quality pre-owned merchandise. Call or text us today.",
 514:"Sell gold in Virginia at any of Valley Pawn's 5 Shenandoah Valley stores. Free appraisal, same-day cash, and offers based on live market rates. Call or text.",
 509:"Sell gold in Culpeper, VA. Free on-the-spot appraisal, same-day cash, and a fair offer based on live market rates. Open Mon-Sat. Call or text before you come.",
 510:"Sell gold in Waynesboro, VA. Free appraisal while you wait, same-day cash, and honest offers based on live market rates. Call or text Valley Pawn today.",
 511:"Sell gold in Harrisonburg, VA. Free appraisal, same-day cash, and a fair offer based on live market rates. Call or text Valley Pawn on East Market Street.",
 512:"Sell gold in Lexington, VA. Free on-the-spot appraisal, same-day cash, and offers based on live market rates. Call or text Valley Pawn on Walker Street.",
 513:"Sell gold in Roanoke, VA. Free appraisal, same-day cash, and a fair offer based on live market rates. Call or text Valley Pawn on Peters Creek Road.",
 591:"Sell jewelry in Virginia - rings, diamonds, watches and more. Free appraisal and same-day cash at all 5 Valley Pawn locations. Call or text before you come in.",
 594:"Sell jewelry in Culpeper, VA. Rings, diamonds, gold chains and watches appraised free, with same-day cash. Call or text Valley Pawn on James Madison Hwy.",
 595:"Sell jewelry in Waynesboro, VA. Rings, diamonds, watches and gold appraised free, same-day cash. Call or text Valley Pawn on West Broad Street.",
 596:"Sell jewelry in Harrisonburg, VA. Free appraisal on rings, diamonds, watches and gold, with same-day cash. Call or text Valley Pawn on East Market Street.",
 597:"Sell jewelry in Lexington, VA. Rings, diamonds, watches and gold appraised free, with same-day cash. Call or text Valley Pawn on Walker Street.",
 598:"Sell jewelry in Roanoke, VA. Free appraisal on rings, diamonds, watches and gold, same-day cash. Call or text Valley Pawn on Peters Creek Road.",
 592:"Sell silver in Virginia - sterling, coins, flatware and bars. Free appraisal and same-day cash at all 5 Valley Pawn stores. Call or text before you come in.",
 599:"Sell silver in Culpeper, VA. Sterling, coins, flatware and bars appraised free, with same-day cash. Call or text Valley Pawn on James Madison Hwy.",
 600:"Sell silver in Waynesboro, VA. Sterling, coins, flatware and bars appraised free, same-day cash. Call or text Valley Pawn on West Broad Street.",
 601:"Sell silver in Harrisonburg, VA. Free appraisal on sterling, coins, flatware and bars, with same-day cash. Call or text Valley Pawn on East Market Street.",
 602:"Sell silver in Lexington, VA. Sterling, coins, flatware and bars appraised free, with same-day cash. Call or text Valley Pawn on Walker Street.",
 603:"Sell silver in Roanoke, VA. Free appraisal on sterling, coins, flatware and bars, same-day cash. Call or text Valley Pawn on Peters Creek Road.",
 593:"Sell coins in Virginia - gold, silver and collectible coins appraised free at all 5 Valley Pawn stores, with same-day cash. Call or text before you come in.",
 604:"Sell coins in Culpeper, VA. Gold, silver and collectible coins appraised free, with same-day cash. Call or text Valley Pawn on James Madison Hwy.",
 605:"Sell coins in Waynesboro, VA. Gold, silver and collectible coins appraised free, same-day cash. Call or text Valley Pawn on West Broad Street.",
 606:"Sell coins in Harrisonburg, VA. Free appraisal on gold, silver and collectible coins, with same-day cash. Call or text Valley Pawn on East Market Street.",
 607:"Sell coins in Lexington, VA. Gold, silver and collectible coins appraised free, with same-day cash. Call or text Valley Pawn on Walker Street.",
 608:"Sell coins in Roanoke, VA. Free appraisal on gold, silver and collectible coins, same-day cash. Call or text Valley Pawn on Peters Creek Road.",
 609:"What your jewelry is really worth, and how Valley Pawn appraises it. Rings, diamonds, watches and gold - free appraisals at 5 Virginia locations.",
 610:"What your silver is really worth, and how Valley Pawn prices it. Sterling, coins, flatware and bars - free appraisals at 5 Virginia locations.",
 611:"What your coins are really worth, and how Valley Pawn appraises them. Gold, silver and collectible coins - free appraisals at 5 Virginia locations.",
 225:"Quality pre-owned hand and power tools at Valley Pawn - big brands for far less than new, all backed by a 30-day warranty. Five Virginia locations.",
 226:"Quality pre-owned electronics at Valley Pawn - laptops, TVs, consoles and audio for less than retail, backed by a 30-day warranty. Five Virginia stores.",
 227:"Fine jewelry at Valley Pawn for a fraction of retail - rings, chains, diamonds and watches, each backed by a 30-day warranty. Five Virginia locations.",
 228:"Collectibles and unique finds at Valley Pawn. New items arrive daily across our 5 Virginia stores, all backed by a 30-day warranty.",
 229:"Pre-owned guitars, amps, brass and more at Valley Pawn - quality instruments for far less than new, backed by a 30-day warranty. Five Virginia locations.",
}
NOINDEX = [748,749,750,751,752,753,569,832,1110]
