---
name: nics-selector-autofix
description: When the Bravo pipeline is idle, smoke-test the already-applied NICS saved-report selector fix (content-matching) on Roanoke, report to Joshua, and self-disable. Selector edit + AHK validation already done 2026-06-22.
---

AUTONOMOUS TASK — verify the NICS-transfers saved-report SELECTOR FIX that was already applied on 2026-06-22, then self-disable. Runs every 15 min; does real work ONLY when the Bravo pipeline is idle, otherwise exits silently. Self-DISABLES via mcp__scheduled-tasks__update_scheduled_task (enabled:false) on success OR hard blocker so it stops running.

WHAT IS ALREADY DONE (do NOT redo): On 2026-06-22 the selector fix was applied to reports/NicsTransfers.ahk and the watcher reloaded. The bottom-most-combo selection was replaced with CONTENT-MATCHING: new helpers NicsSelectSavedReport + NicsCollectSavedReportCombos walk every Edit/BravoComboBox (skipping autoIds BoxColumns/BoxIsShared/BoxSelectCriteria), open each (bottom-most first), and pick the combo whose dropdown actually contains "Claude NICS Transfers"; falls back to the shared SelectSavedReport if none match. The existing verify-via-IntakeGetLoadedReportName retry is preserved. Backup: reports/NicsTransfers.ahk.bak-pre-selectorfix-2026-06-22. AHK syntax was validated (full watcher loaded clean via /iLib, balanced braces). The handler runs the report via the bottom "Ok" (IntakeClickOkVerified) and runs AS-SAVED (no date typing — calendar picker only, leave as-is). DO NOT re-run nics_combo_diag.ahk — it enumerates UIA Type "ComboBox" but Bravo's combo is Type "Edit" Name "BravoComboBox", so it returns NO-MATCH/hangs; it is a dead end. Only file you may ever edit is reports/NicsTransfers.ahk.

ENV: All filesystem/VM access to the Bravo Data Extraction folder MUST go through mcp__Control_your_Mac__osascript do shell script. PROJECT DIR: /Users/joshuadavis/Documents/Claude/Projects/Bravo Data Extraction (Windows/Y: path Y:\Documents\Claude\Projects\Bravo Data Extraction). VM UUID for prlctl: {7dc84f03-4e68-4f43-9596-bf8a7dfb8e0a}. prlctl at /usr/local/bin/prlctl (fallback /Applications/Parallels Desktop.app/Contents/MacOS/prlctl). Slack DM ONLY to Joshua user U03BB52MDSA — never public channels.

STEP 1 — IDLE GUARD. Via osascript check: find "<DIR>/results" -name '*.result.json' -mmin -6 ; ls "<DIR>/triggers/" for any pending *.json (ignore the subdirs claimed/processed/killed/payloads/staging/_hold) ; ls "<DIR>/triggers/claimed/" for a very recent claim ; and whether the newest per-run log (exclude foreground_keeper.log/watchdog.log/watcher.last_started.txt) changed in the last ~5 min. If ANY run looks active OR a trigger is pending/in-flight, EXIT SILENTLY (do nothing, no Slack). Only proceed when fully idle.

STEP 2 — SMOKE TEST. Drop a trigger file into <DIR>/triggers/ named nics-autofix-ROA-<ts>.json with content: {"id":"nics-autofix-ROA-<ts>","requested_at":"<iso>","reports":[{"name":"nics-transfers","stores":["ROA"],"date":"2026-06-17"}]}. Write it via osascript (e.g. python3 or printf). Poll logs/nics-autofix-ROA-<ts>.log and results up to ~4 min. SUCCESS = result status success AND the output CSV output/2026-06-17_to_2026-06-17_ROA_nics-transfers.csv has data rows (more than the single header line) including a fee/amount column with ~$25 values. If the watcher does not claim the trigger within ~2 min, it is not idle after all — delete your trigger if still pending and EXIT SILENTLY (try again next run).

STEP 3 — REPORT + SELF-DISABLE. DM Joshua (U03BB52MDSA): whether the ROA smoke returned rows (with a sample of the fee column), and the exact next step (run all 5 stores trailing-12-month, then set up weekly/monthly recurring cells). If SUCCESS → disable this task (mcp__scheduled-tasks__update_scheduled_task taskId 'nics-selector-autofix' enabled:false) and tell Joshua it is ready for the full pull. If the smoke returns 0 rows OR errors, DM Joshua the specifics (log tail + what happened) and ALSO disable the task so it stops looping — do not retry blindly. Keep Bravo on a clean Dashboard when done (the handler's pre-flight Cancel + BackToDashboard handle this).