---
name: gdrive-cache-refresh
description: Refresh the Google Drive cache used by Joshua's unified-search (vpfind --gdrive)
model: claude-sonnet-5
---

You are refreshing the Google Drive cache for Joshua's local "Unified Search" system (vpfind). This is a recurring nightly task with no memory of any prior conversation — everything you need is below.

BACKGROUND: Joshua has a local SQLite FTS5 search index covering Apple Mail, iMessage/SMS, iCloud Drive, Apple Notes, Apple Reminders, and Google Drive, queried via a CLI called `vpfind`. Everything except Google Drive is indexed directly by a nightly local script. Google Drive is different: the Google Drive MCP connector only exists inside a live Cowork session like this one, so a local script can't call it. Instead, THIS scheduled task populates a local JSONL cache file, and a separate local nightly rebuild (launchd, ~3:30 AM, after this task) just ingests whatever is in that cache into the search index. Your job is only to refresh the cache — you do not need to touch the search index or run any Python yourself.

CACHE FILE: `~/Documents/Claude/Projects/Unified Search/gdrive_cache/latest.jsonl` — one JSON object per line, UTF-8, schema:
`{"name": <file title>, "folder": <best-effort folder/path label>, "body": <extracted plaintext, cap ~60000 chars>, "path_or_url": <Drive webViewLink or a docs.google.com/drive.google.com URL built from the file id>, "mtime": <ISO 8601 modifiedTime string>, "size": <int, bytes, 0 if unknown>, "mime_type": <string>}`

WHAT TO DO, IN ORDER:
1. Read the Google Drive connector tool names available to you this session (they'll be named like `mcp__<id>__list_recent_files`, `search_files`, `read_file_content`, `download_file_content`, `get_file_metadata`). If no Google Drive connector is available this session, stop and do nothing further (do not error loudly — Joshua may not have the connector attached to every session; just end quietly, this task will simply try again tomorrow).
2. Determine the "since" cutoff: read the existing `gdrive_cache/latest.jsonl` if it exists, find the maximum `mtime` value across all lines, and use that as your lower bound (if the file doesn't exist yet or is empty, use "7 days ago" as a reasonable first cutoff). Read the file with a normal file-read tool against the path above — it lives on the real Mac filesystem, already reachable in this session.
3. Call `list_recent_files` (orderBy `lastModified`, excludeContentSnippets true, paginate as needed) and/or `search_files` with a `modifiedTime > '<cutoff>'` query, to enumerate files modified since the cutoff. Cap yourself at roughly 300 files this run — if there are more, take the most recently modified 300 and let tomorrow's run pick up the rest (coverage is meant to expand gradually, not exhaustively in one pass).
4. For each candidate file, skip: images (mimeType starting `image/`), video/audio, folders (`application/vnd.google-apps.folder`), other binaries with no text-extraction path, and anything over ~50MB. Prioritize Google Docs, Google Sheets, Google Slides, PDFs, and plain text/markdown/CSV files — these are the types worth indexing.
5. For Google-native files (Docs/Sheets/Slides) and PDF/Office formats, use `read_file_content` to get a natural-language text representation. For plain text/markdown/CSV/JSON files, use `download_file_content` (base64-decode it) since `read_file_content`'s documented supported-mimetype list doesn't include plain text. Truncate extracted body text to ~60,000 characters.
6. For `folder`, use the parent folder's name if you can resolve it cheaply via `get_file_metadata` on the parentId (don't burn excessive calls chasing full paths — a single-level folder name is good enough, blank is acceptable if resolving it is expensive).
7. Build one JSON object per successfully-extracted file per the schema above and APPEND them to `~/Documents/Claude/Projects/Unified Search/gdrive_cache/latest.jsonl` (append, do not overwrite — the nightly local ingest step (`usearch.py gdrive`) does a full DELETE+reload of the SQLite table from whatever is in this file each night, so duplicates across runs are only a minor inefficiency, not a correctness problem; if you want to be tidy, you may instead rewrite the whole file de-duplicated by file id, keeping the newest entry per id, but a simple append is perfectly fine).
8. Do not write anything else to that directory. Do not touch `index.db` or any `.py` files. Do not attempt to run `python3 usearch.py gdrive` yourself — that happens locally in the nightly launchd rebuild (`refresh.sh`, ~3:30 AM), after this task.
9. End with a short internal summary line (e.g. "gdrive cache: appended N files, cutoff was <date>") — no need to message Joshua about routine successful runs. If something structural breaks (e.g. the connector is gone for multiple days in a row, or writes are failing), that's worth a note, but a normal small nightly delta is not.

This task exists so Google Drive search coverage (`vpfind --gdrive` / `vpfind --drive`) grows over time without Joshua having to do anything. The very first cache (a ~30-file seed prioritizing Docs/Sheets/PDFs, including several genuinely useful tax/entity/business documents) was built manually in a one-time session on 2026-08-10 — this recurring task is what keeps it growing and current from here on.