---
name: vp-website-shop-nightly
description: Refresh thevalleypawn.com/shop/ twice daily (7am & 3pm ET) — pulls all 5 stores' full live eBay inventory, filters weapons-adjacent, rebuilds the searchable buy-now grid, writes it to the /shop/ page (WP page id 833) via the site REST API, posts summary to #website. Sold items drop off automatically. Additive; never touches /retail/.
---

Refresh Valley Pawn's online store at https://thevalleypawn.com/shop/ with the FULL current eBay inventory from all 5 stores. This is ADDITIVE — never touch /retail/ or any other page/task. Use the Claude in Chrome browser tools (the browser is logged into eBay and WordPress via saved passwords; never ask anyone to log in).

METHOD (this exact browser-only method is proven to work — follow it):

STEP 1 — Collect all 5 stores from eBay's PUBLIC seller search (no login needed). For each store below, navigate to the URL, wait for load, then run the EXTRACTOR script and accumulate results in the tab's localStorage under key 'vpAll'. Stores (name -> ebay username): Culpeper->valley_pawn_culpeper, Waynesboro->valley_pawn_waynesboro, Harrisonburg->valley_pawn_harrisonburg, Lexington->valley_pawn_lexington, Roanoke->valley_pawn_roanoke.
URL per store: https://www.ebay.com/sch/i.html?_ssn=<USERNAME>&_ipg=240&_sop=10  — if a store returns exactly 240 items, ALSO load page 2 (append &_pgn=2) and merge (dedupe by item URL). (Culpeper has ~300, needs page 2.)

On the FIRST store, initialize:  localStorage.setItem('vpAll', JSON.stringify({colors:{"Culpeper":"#0099DD","Waynesboro":"#2D1A5E","Harrisonburg":"#E07A5F","Lexington":"#3DB8E8","Roanoke":"#2A9D8F"}, items:[]}));
EXTRACTOR (run per page; STORE is the store name string):
function extract(store){var seen=new Set(),items=[];document.querySelectorAll('a[href*="/itm/"]').forEach(function(a){var m=a.href.match(/itm\/(\d+)/);var itm=m&&m[1];if(!itm||seen.has(itm))return;var box=a;for(var i=0;i<7&&box;i++){if(box.querySelector&&box.querySelector('img')&&/\$[\d,]/.test(box.textContent))break;box=box.parentElement;}if(!box)return;var img=box.querySelector('img');var isrc=img?(img.getAttribute('src')||img.getAttribute('data-src')||img.currentSrc||''):'';var pe=[].slice.call(box.querySelectorAll('span,div')).find(function(e){return /^\$[\d,]+\.?\d*$/.test(e.textContent.trim())});var p=pe?pe.textContent.trim():'';var t=(a.getAttribute('aria-label')||a.textContent||'').trim();if(!t){var h=box.querySelector('[role=heading],h3');t=h?h.textContent.trim():'';}t=t.replace(/\s*Opens in a new window or tab\s*/i,'').replace(/\s+/g,' ').trim();var ig=(isrc.match(/\/g\/([^/]+)\//)||[])[1]||'';if(t&&p&&ig&&!/Shop on eBay/i.test(t)){seen.add(itm);items.push({t:t,p:p,u:'https://www.ebay.com/itm/'+itm,img:'https://i.ebayimg.com/images/g/'+ig+'/s-l500.webp',s:store});}});return items;}
To accumulate after each page: read db=JSON.parse(localStorage.getItem('vpAll')); have=new Set(db.items.map(x=>x.u)); add=extract('<Store>').filter(x=>!have.has(x.u)); db.items=db.items.concat(add); localStorage.setItem('vpAll',JSON.stringify(db));

STEP 2 — Build the page block IN THE BROWSER and stash it in window.name (so it survives navigating to the WordPress origin). Run this builder (it filters weapons-adjacent items, renders static cards + search/filter/sort script, and wraps everything in a wp:html block with VP-SHOP markers). Use the EXACT builder from the working run: read db=JSON.parse(localStorage.getItem('vpAll')); COLORS=db.colors; BAN=/\b(gun|guns|rifle|pistol|handgun|firearm|ammo|ammun|magazine|tactical|holster|silencer|suppressor|scope|red dot|optic|bayonet|knife|blade|dagger|machete)\b/i; keep items where !BAN.test(t); sort by store order [Culpeper,Waynesboro,Harrisonburg,Lexington,Roanoke]; produce for each item an <article class="vp-card" data-store data-title(lowercased title+store) data-price(numeric)> with image (i.img), store badge (COLORS[s]), title link, price, and a "Buy Now" link — all links href=i.u target=_blank rel="noopener nofollow". Include the same <style>, a .vp-lead intro, a .vp-srow with #vpSearch input + #vpSort select (Featured/Low-High/High-Low) + #vpCount span, .vp-chips (All Stores + one chip per store with counts), the .vp-grid of cards, a .vp-empty message, a .vp-foot with total, and the search <script>. Wrap as: `<!-- wp:html --><!-- VP-SHOP-START --><div class="vp-shop-app">...<!-- VP-SHOP-END --><!-- /wp:html -->`. Then: window.name = block; and remember counts per store + total + filteredOut. (The full builder JS is saved at /Users/joshuadavis/Documents/Claude/Projects/Website/shop-build/generate_shop_block.py for reference — same output.)

STEP 3 — Publish to WordPress via the site's own REST API (no connector needed). Navigate the SAME tab to https://thevalleypawn.com/wp-admin/ (window.name persists across this navigation). Then run:
const block=window.name; const nonce=await fetch('/wp-admin/admin-ajax.php?action=rest-nonce',{credentials:'include'}).then(r=>r.text()); const res=await fetch('/wp-json/wp/v2/pages/833',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','X-WP-Nonce':nonce.trim()},body:JSON.stringify({content:block,status:'publish'})}); const j=await res.json();
Confirm res.status is 200 and j.id is 833. (Page id 833 = the /shop/ page.)

STEP 4 — Verify: navigate to https://thevalleypawn.com/shop/?v=<timestamp> and confirm document.querySelectorAll('.vp-shop-app .vp-card').length equals the built total.

STEP 5 — Post a summary to Slack #website (channel C0ASE9C0GQ0): ":shopping_trolley: *Shop refreshed* — thevalleypawn.com/shop/" with per-store counts (Culpeper, Waynesboro, Harrisonburg, Lexington, Roanoke), the total live count, and how many weapons-adjacent items were excluded. On ANY failure (extraction, publish non-200, verify mismatch): do NOT post success — instead DM Joshua on Slack (user U03BB52MDSA) with what failed and at which step.

Notes: eBay public seller-search needs no login. Everything stays in the browser (window.name holds the ~470KB block) so nothing large passes through your context. Keep it additive.